In [1]:
import pandas as pd

In [2]:
df = pd.read_excel(r'/Users/joaquinmorales13a06/Desktop/Data Engineering Projects/sydney-rental-tracker/data/raw/lodgements_2024_05.xlsx', header=2)
df

      Lodgement Date  Postcode Dwelling Type Bedrooms Weekly Rent
0         2024-05-22      2000             F        0         700
1         2024-05-16      2000             F        0        1000
2         2024-05-01      2000             F        0         640
3         2024-05-31      2000             F        0         640
4         2024-05-07      2000             F        0         650
...              ...       ...           ...      ...         ...
28663     2024-05-23      2880             O        1         170
28664     2024-05-01      2880             T        1         220
28665     2024-05-13      2880             U        U         300
28666     2024-05-13      2880             U        U         270
28667     2024-05-13      2880             U        U         300

[28668 rows x 5 columns]

In [8]:
# check for the data types of each column
df.dtypes

# transform Weekly Rent column from str to float
df['Weekly Rent'] = pd.to_numeric(df['Weekly Rent'], errors='coerce')
df.dtypes

Lodgement Date    datetime64[us]
Postcode                   int64
Dwelling Type                str
Bedrooms                     str
Weekly Rent              float64
dtype: object

In [9]:
# Explore statistics on the dataframe data
df.describe()

                   Lodgement Date      Postcode   Weekly Rent
count                       28668  28668.000000  28268.000000
mean   2024-05-15 22:20:02.511511   2269.536801    709.251274
min           2024-05-01 00:00:00   2000.000000      1.000000
25%           2024-05-08 00:00:00   2070.000000    505.000000
50%           2024-05-16 00:00:00   2174.000000    650.000000
75%           2024-05-24 00:00:00   2452.000000    819.000000
max           2024-05-31 00:00:00   2880.000000   7500.000000
std                           NaN    243.092770    347.299397